### ISSUE TITLE
Workflow todo

### ISSUE THREAD

**Issue by fdreyer** [JetsGame/GroomRL#3]
* [x] Add testing plots and stats on mass median/window to the output of a run in a test/ folder, using the plot_lund, plot_mass routines in scripts/plotting/test.py
* [x] Decide on whether we save only the weights (more lightweight but requires knowledge of architecture, which can be encoded in the json file containing hyperparameters), or if we save the full model as hdf5 (more overhead but somewhat easier to handle)
* [x] For later: write an interface for fastjet which can load in the keras model and apply the grooming to a JetTree (which also needs to be ported to C++). We could implement it as a fj-contrib but probably should to ask Gavin about tensorflow dependency. 
  * For this usecase, it might be better to have output of the full model from the python code?
  * Also need to implement the Keras-rl test policy in c++, but that looks pretty easy.
